# Generated by Django 5.0.2 on 2024-02-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_payment_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
