# Generated by Django 5.0.2 on 2024-02-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='url_payment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='адрес оплаты'),
        ),
    ]
