# Generated by Django 5.0.2 on 2024-03-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_course_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='amount',
            new_name='price',
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='цена'),
        ),
    ]
